package com.mcai.posingcoach.service;

/**
 * Callback interface for the PoseProcessorService asynchronous operations.
 */
public interface PoseCallback {
    /**
     * Called when the AI processing completes successfully.
     *
     * @param sketchUrl The URL of the generated sketch image.
     * @param guideText The guide text generated by the AI (or default if missing).
     */
    void onSuccess(String sketchUrl, String guideText);

    /**
     * Called when an error occurs during processing (network error, API error, etc.).
     *
     * @param errorMessage A descriptive error message to show to the user.
     */
    void onError(String errorMessage);
}
